# use_wandb: False

task_config:
    language: 'en'
    output_path: dump
    workers: 5
    max_usage: 10000
    task_description: You are a professional classifier who will classify the content of the promotional material and inform the user whether the content is a qualified promotional material.
    instruction: Is the content of this promotional material acceptable? Please answer yes or no.
    samples_per_step: 10
    batch_size: 10
    max_samples: 50
    num_steps: 3
    warmup: 4
    history_length: 4
    label_schema: ["Yes", "No"]
    num_errors_per_label: 5
    num_extra_sample: 5
    patience: 10
    min_delta: 0.1
    
eval_config:
    label_schema: ["Yes", "No"]
    func_name: accuracy
    num_errors_per_label: 5

model_config:
    generation:
        module_name: 'openai_post'
        model_name: 'gpt-4o'
        max_tokens: 2000
        seed: 1234
        temperature: 0.1

    annotator:
        module_name: 'openai_post'
        model_name: 'gpt-4o'
        max_tokens: 2000
        seed: 1234

    # annotator:
#     method : 'argilla'
#     config:
#         api_url: ''
#         api_key: 'admin.apikey'
#         workspace: 'admin'
#         time_interval: 5

    predictor:
        module_name: 'openai_post'
        model_name: 'gpt-4o'
        max_tokens: 2000
        seed: 1234

    analyzer:
        module_name: 'openai_post'
        model_name: 'gpt-4o'
        max_tokens: 2000
        seed: 1234

# stop_criteria:
#     max_usage: 2 #In $ in case of OpenAI models, otherwise number of tokens
#     patience: 10 # Number of patience steps
#     min_delta: 0.01 # Delta for the improvement definition
