# use_wandb: False

task_config:
    language: 'en'
    output_path: dump
    # input_path: dump
    workers: 5
    max_usage: 10000
    task_description: An assistant is a staff member who is good at writing work reports.
    instruction: Please write an environmental report.
    label_schema: ["1","2","3","4","5"]
    num_steps: 2
    samples_per_step: 3
    batch_size: 2
    max_samples: 50
    warmup: 4
    history_length: 4
    num_errors_per_label: 5
    num_extra_sample: 5
    patience: 10
    min_delta: 0.1

eval_config:
    label_schema: ["1","2","3","4","5"]
    func_name: accuracy
    num_errors_per_label: 5

model_config:
    generation:
        module_name: 'openai_post'
        model_name: 'gpt-4o'
        max_tokens: 2000
        seed: 1234
        temperature: 0.1

    annotator:
        module_name: 'openai_post'
        model_name: 'gpt-4o'
        max_tokens: 2000
        seed: 1234

    predictor:
        module_name: 'openai_post'
        model_name: 'gpt-4o-mini'
        max_tokens: 2000
        seed: 1234

    analyzer:
        module_name: 'openai_post'
        model_name: 'gpt-4o'
        max_tokens: 2000
        seed: 1234