# use_wandb: False

task_config:
    language: 'cn'
    output_path: dump
    input_path: dump
    workers: 5
    max_usage: 10000
    task_description: 助手是一个善于撰写工作报告的工作人员。
    instruction: 请撰写一份环保报告。
    samples_per_step: 3
    batch_size: 2
    max_samples: 50
    num_steps: 2
    warmup: 4
    history_length: 4
    label_schema: ["1","2","3","4","5"]
    num_errors_per_label: 5
    num_extra_sample: 5
    patience: 10
    min_delta: 0.1

eval_config:
    label_schema: ["1","2","3","4","5"]
    func_name: ranking
    num_errors_per_label: 5
    instruction:
    batch_size: 1
    error_threshold: '4'

ranker_config:
    instruction: 请帮我写一个环保报告。
    label_schema: ["1","2","3","4","5"]

model_config:
    generation:
        module_name: 'dashscope_generation'
        model_name: 'qwen2-57b-a14b-instruct'
        max_tokens: 2000
        seed: 1234

    annotator:
        module_name: 'dashscope_generation'
        model_name: 'qwen2-72b-instruct'
        max_tokens: 2000
        seed: 1234

    predictor:
        module_name: 'dashscope_generation'
        model_name: 'qwen2-57b-a14b-instruct'
        max_tokens: 2000
        seed: 1234

    analyzer:
        module_name: 'dashscope_generation'
        model_name: 'qwen2-72b-instruct'
        max_tokens: 2000
        seed: 1234

    evaluator:
        module_name: 'dashscope_generation'
        model_name: 'qwen2-72b-instruct'
        max_tokens: 2000
        seed: 1234
