# use_wandb: False

task_config:
    language: 'cn'
    output_path: dump
    max_usage: 6000
    task_description: 助手是一个数学家。
    instruction: 判断计算算式的结果是否正确，回答是或者否。
    samples_per_step: 10
    batch_size: 10
    workers: 5

model_config:
    generation:
        module_name: 'dashscope_generation'
        model_name: 'qwen2-57b-a14b-instruct'
        max_tokens: 2000
        seed: 1234