# use_wandb: False

task_config:
    language: 'en'
    output_path: dump
    max_usage: 6000
    task_description: Assistant is a mathematician.
    instruction: Determine whether the result of the calculation is correct. Respond with "yes" or "no".
    samples_per_step: 10
    batch_size: 10
    workers: 5

model_config:
    generation:
        module_name: 'openai_post'
        model_name: 'gpt-4o'
        max_tokens: 2000
        seed: 1234
