icl_configs:
  BM25_index_pth: data/icl_bm25_demo/demonstrations_2024-07-02 12:09:11
  topk: 3
  embedding_retriever_configs:
    embedding_pth: data/app_data/agent_followup_data/icl_data/agent_role_emb_model:<text_embedding_v2>_search_key:['chat_history',
      'last_query']_examples_ver_2024-07-16 14:27:09.npy
    embedding_model: text_embedding_v2
    search_key:
    - chat_history
    - last_query
    examples_pth: data/app_data/agent_followup_data/icl_data/agent_role_icl_examples_ver_2024-07-16
      14:27:09.json
task_configs:
  base_model: Qwen_14B
  num_questions: 3
