icl_configs:
  topk: 3
  embedding_retriever_configs:
    embedding_pth: data/app_data/agent_followup_data/icl_data/agent_role_followup_emb_model:<text_embedding_v2>_search_key:['system_prompt',
      'chat_history', 'last_query']_examples_ver_2024-08-01 15:52:48.index
    embedding_model: text_embedding_v2
    search_key:
    - system_prompt
    - chat_history
    - last_query
    examples_pth: data/app_data/agent_followup_data/icl_data/agent_role_followup_icl_examples_ver_2024-08-01
      15:52:47.json
  BM25_retriever_configs:
    examples_list_pth: data/app_data/agent_followup_data/demonstrations/role_followups_full_reformat.json
    BM_25_index_dir: data/app_data/agent_followup_data/icl_data_bm25/agent_role_demonstrations_2024-07-16
      16:14:39
    search_key:
    - chat_history
    - last_query
task_configs:
  num_questions: 3
  base_model: qwen2-57b-a14b-instruct
  model_config:
    generation:
      module_name: dashscope_generation
      model_name: qwen2-57b-a14b-instruct
      clazz: models.llama_index_generation_model
      max_tokens: 2000
      seed: 1234
