icl_configs:
  topk: 3
  embedding_retriever_configs:
    embedding_pth: data/app_data/agent_followup_data/icl_data/agent_role_followup_emb_model:<text_embedding_v2>_search_key:['system_prompt',
      'chat_history', 'last_query']_examples_ver_2024-07-23 13:34:00.npy
    embedding_model: text_embedding_v2
    search_key:
    - system_prompt
    - chat_history
    - last_query
    examples_pth: data/app_data/agent_followup_data/icl_data/agent_role_followup_icl_examples_ver_2024-07-23
      13:34:00.json
  BM25_retriever_configs:
    examples_list_pth: data/app_data/agent_followup_data/demonstrations/role_followups_full_reformat.json
    BM_25_index_dir: data/app_data/agent_followup_data/icl_data_bm25/agent_role_demonstrations_2024-07-16
      16:14:39
    search_key:
    - chat_history
    - last_query
task_configs:
  base_model: qwen_14b
  num_questions: 3
