num_expand: 5
demonstration_generation_instruction:  "请根据提供的样例，给出${num_generated_examples}个类似样例，要求和现在的样例的任务类型一致。\n\n要求：\n1. 生成的语言和提供的参考样例保持一致， 即提供的参考样例是英文的，你给出的样例也应该是英文的；如果提供的参考样例是中文的，你给出的样例也应该是中文的\n2. 给出的样例尽量与参考样例属于同一个任务类型，但和参考样例有较大区别，并且是不同domain的。\n3. 和提供的参考样例保持一致输出格式，并且每个样例必须用markdown json形式单独区分。即输出形式:\n```json\n你生成的样例1\n```\n\n```json\n你生成的样例2\n```\n\n${other_requirements}\n\n参考样例：\n${demonstration}\n\n\n请给出${num_generated_examples}个类似样例:"
demonstration_requirements: ""
demonstration_dir: "examples/gsm8k_example/results"
model_config:
  module_name: 'aio_generation'
  model_name: qwen-max-allinone
  clazz: 'models.llama_index_generation_model'
  max_tokens: 2000
  seed: 1234
  temperature: 1