icl_configs:
  BM25_index_pth: data/icl_bm25_demo/demonstrations_2024-07-02 12:09:11
  examples_pth: data/app_data/agent_followup_data/icl_data/agent_role_icl_examples_ver_2024-07-15
    17:04:43.json
  topk: 3
  retriever_key_list:
  - chat_history
  - last_query
  embedding_pth: data/app_data/agent_followup_data/icl_data/agent_role_emb_model:<text_embedding_v2>_search_key:['chat_history',
    'last_query']_examples_ver_2024-07-15 17:04:44.npy
  embedding_model: text_embedding_v2
task_configs:
  base_model: Qwen_14B
  num_questions: 3
