# use_wandb: False
language: 'en'
task_description: Assistant is a mathematician.
instruction: Determine whether the result of the calculation is correct. Respond with "yes" or "no".
samples_per_step: 10
batch_size: 10
workers: 5
